{
  "resourceType": "Condition",
  "id": "covid-19-confirmed-759f",
  "meta": {
    "profile": [ "http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-condition" ]
  },
  "category": [ {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/condition-category",
      "code": "encounter-diagnosis",
      "display": "Encounter Diagnosis"
    } ]
  } ],
  "code": {
    "coding": [ {
      "system": "http://snomed.info/sct",
      "version": "2022-09",
      "code": "840539006",
      "display": "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)",
      "userSelected": true
    } ]
  },
  "subject": {
    "reference": "Patient/81aa698c-8d2d-49ed-8782-efa4c96b8cc3"
  }
}